# https://taskfile.dev

version: "3"

tasks:
  assets:
    cmds:
      - 'freeze -o lipgloss.png --execute "go run ./lipgloss/main.go"'
      - "vhs bubbletea.tape"
      - "vhs bubbletea-bubbles.tape"
      - "vhs wish.tape"
      - "vhs wish-auth.tape"
